#Database
POSTGRESQL_USERNAME: user
POSTGRESQL_PASSWORD: password
POSTGRESQL_HOST: postgrescontainer
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: filedatabase

#Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: prod

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: zzz12den24@gmail.com
EMAIL_PASSWORD: rfv467(89m)gh
VERIFY_EMAIL_HOST: http://localhost:8085