#Database
POSTGRESQL_USERNAME: user
POSTGRESQL_PASSWORD: password
POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5433
POSTGRESQL_DATABASE: filedatabase

#Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: hixoti3916@adosnan.com
EMAIL_PASSWORD: hixoti3916@adosnan.com
VERIFY_EMAIL_HOST: http://localhost:8085